'use client';
import {messenger,miniApp} from '@/lib/messenger';
import {useState} from 'react';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
export default function AdminPanel({onPublished}:{onPublished:()=>void}){
 const [user,setUser]=useState<{firstName:string;id:number}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[preview,setPreview]=useState(false);
 async function request(path:string,data?:unknown){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','x-messenger':messenger(),'x-telegram-init-data':miniApp()?.initData||''},body:data?JSON.stringify(data):undefined});const j=await r.json() as {user?:{firstName:string;id:number};error?:string};if(!r.ok)throw Error(j.error||'ارتباط برقرار نشد.');return j}
 async function login(){setBusy(true);setMessage('');try{const r=await request('/api/admin/session');setUser(r.user!)}catch(e){setMessage(e instanceof Error?e.message:'ورود انجام نشد.')}finally{setBusy(false)}}
 async function publish(){setBusy(true);setMessage('');try{await request('/api/admin/notices',{title,body});setTitle('');setBody('');setPreview(false);setMessage('اطلاعیه در مینی‌اپ منتشر شد.');onPublished()}catch(e){setMessage(e instanceof Error?e.message:'انتشار انجام نشد.')}finally{setBusy(false)}}
 return <section className="admin-panel"><div className="page-title"><h1>مدیریت آلیس</h1><p>{user?'مدیر اصلی · '+user.firstName:'ورود امن با حساب پیام‌رسان'}</p></div>{!user?<div className="white-card"><p>با حساب مدیر، مینی‌اپ را از دکمه «ورود به مجموعه آلیس» در بات باز کن و وارد شو.</p><Button className="primary" disabled={busy} onClick={()=>void login()}>{busy?'در حال بررسی…':'ورود با حساب پیام‌رسان'}</Button><a className="text-link" href={messenger()==='bale'?'https://ble.ir/alicesportclubbot':'https://t.me/AliceSportClubBot'}>رفتن به بات آلیس</a></div>:<><div className="white-card"><p>شناسه مدیر: <bdi>{user.id}</bdi></p><p className="eyebrow">دسترسی: انتشار اطلاعیه در مینی‌اپ</p></div><form className="white-card" onSubmit={e=>{e.preventDefault();setPreview(true);setMessage('')}}><h2>اطلاعیه جدید</h2><label htmlFor="notice-title">عنوان</label><Input id="notice-title" required maxLength={120} value={title} disabled={busy} onChange={e=>{setTitle(e.target.value);setPreview(false)}}/><label htmlFor="notice-body">متن اطلاعیه</label><Textarea id="notice-body" required maxLength={1600} rows={6} value={body} disabled={busy} onChange={e=>{setBody(e.target.value);setPreview(false)}}/><p className="eyebrow">مقصد انتشار: اطلاعیه‌های مینی‌اپ آلیس</p><Button type="submit" className="secondary" disabled={busy||!title.trim()||!body.trim()}>پیش‌نمایش اطلاعیه</Button>{preview&&<div className="notice"><h3>{title}</h3><p>{body}</p><Button type="button" className="primary" disabled={busy} onClick={()=>void publish()}>{busy?'در حال انتشار…':'تأیید و انتشار در مینی‌اپ'}</Button></div>}</form><Button className="secondary" disabled={busy} onClick={()=>{setUser(null);setMessage('');setTitle('');setBody('');setPreview(false)}}>بستن پنل مدیریت</Button></>}{message&&<p role="status" className="error-note">{message}</p>}</section>
}
