import { z } from 'zod';
const session = z.object({ day:z.string().max(30), start:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), end:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), audience:z.string().max(40) });
const service = z.object({description:z.string().max(2000), singlePrice:z.string().max(80), packagePrice:z.string().max(80), rules:z.string().max(4000), sessions:z.array(session).max(100)});
export const contentSchema = z.object({name:z.string().min(1).max(120), greeting:z.string().max(300), address:z.string().max(500), phone:z.string().max(40), gym:service, pool:service, notices:z.array(z.object({title:z.string().min(1).max(160),body:z.string().max(1600)})).max(30)});
export type Content = z.infer<typeof contentSchema>;
export const initialContent:Content = {
 name:'مجموعه ورزشی آلیس', greeting:'سلام، به آلیس خوش آمدی.', address:'تهران، تهرانپارس، خیابان شهید ملکی، نبش خیابان ۱۲۰، پلاک ۶', phone:'',
 gym:{"description":"برنامه فعالیت باشگاه بدنسازی آلیس.","singlePrice":"","packagePrice":"","rules":"","sessions":[{"day":"شنبه","start":"08:00","end":"16:00","audience":"بانوان"},{"day":"شنبه","start":"16:00","end":"23:00","audience":"آقایان"},{"day":"یکشنبه","start":"08:00","end":"16:00","audience":"بانوان"},{"day":"یکشنبه","start":"16:00","end":"23:00","audience":"آقایان"},{"day":"دوشنبه","start":"08:00","end":"16:00","audience":"بانوان"},{"day":"دوشنبه","start":"16:00","end":"23:00","audience":"آقایان"},{"day":"سه‌شنبه","start":"08:00","end":"16:00","audience":"بانوان"},{"day":"سه‌شنبه","start":"16:00","end":"23:00","audience":"آقایان"},{"day":"چهارشنبه","start":"08:00","end":"16:00","audience":"بانوان"},{"day":"چهارشنبه","start":"16:00","end":"23:00","audience":"آقایان"},{"day":"پنجشنبه","start":"08:00","end":"16:00","audience":"بانوان"},{"day":"پنجشنبه","start":"16:00","end":"23:00","audience":"آقایان"},{"day":"جمعه","start":"08:00","end":"16:00","audience":"بانوان"},{"day":"جمعه","start":"16:00","end":"23:00","audience":"آقایان"}]},
 pool:{"description":"سانس‌های استخر و سونا و ورودی استخر آلیس.","singlePrice":"۸۰۰٬۰۰۰ تومان","packagePrice":"","rules":"","sessions":[{"day":"شنبه","start":"09:00","end":"22:00","audience":"بانوان"},{"day":"یکشنبه","start":"09:00","end":"16:00","audience":"بانوان"},{"day":"یکشنبه","start":"16:00","end":"23:00","audience":"آقایان"},{"day":"دوشنبه","start":"09:00","end":"15:00","audience":"بانوان"},{"day":"دوشنبه","start":"15:00","end":"23:00","audience":"آقایان"},{"day":"سه‌شنبه","start":"09:00","end":"16:00","audience":"بانوان"},{"day":"سه‌شنبه","start":"16:00","end":"23:00","audience":"آقایان"},{"day":"چهارشنبه","start":"09:00","end":"15:00","audience":"بانوان"},{"day":"چهارشنبه","start":"15:00","end":"23:00","audience":"آقایان"},{"day":"پنجشنبه","start":"09:00","end":"16:00","audience":"بانوان"},{"day":"پنجشنبه","start":"16:00","end":"23:00","audience":"آقایان"},{"day":"جمعه","start":"09:00","end":"23:00","audience":"آقایان"}]},
 notices:[]
};
