import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {createHmac} from 'node:crypto';
import {readMembers,exportMembers} from '../src/members.js';
import {readCampaignReport,formatCampaignReport,recentCampaignReports} from '../src/reports.js';
import {validateTelegram} from '../../miniapp/lib/telegram-auth.ts';
import {membersXlsx} from '../../miniapp/lib/members-xlsx.ts';
import {unzipSync,strFromU8} from '../../miniapp/node_modules/fflate/esm/index.mjs';

class D1 {
  constructor(){this.sqlite=new DatabaseSync(':memory:');this.sqlite.exec(readFileSync(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8'));this.sqlite.exec(readFileSync(new URL('../migrations/0002_broadcast_flow.sql',import.meta.url),'utf8'));}
  prepare(sql){const stmt=this.sqlite.prepare(sql);let args=[];return {bind(...v){args=v;return this},async first(){return stmt.get(...args)||null},async all(){return {results:stmt.all(...args)}}};}
}
function database(){const db=new D1();const insert=db.sqlite.prepare('INSERT INTO members(platform,chat,name,subscribed,news_opt_out) VALUES(?,?,?,?,?)');for(let i=1;i<=28;i++)insert.run('telegram',i,i===1?'علي 100%_':'عضو '+i,i===2?0:1,i===2?1:0);insert.run('bale',1,'مدیر',1,0);insert.run('bale',2,'عضو بله',0,0);return db;}

test('members count platform accounts separately and paginate without losing records',async()=>{const db=database();const one=await readMembers(db,{}, {telegram:'1',bale:'1'});const two=await readMembers(db,{page:2});assert.equal(one.total,30);assert.equal(one.members.length,25);assert.equal(two.members.length,5);assert.equal(new Set([...one.members,...two.members].map(m=>m.platform+':'+m.id)).size,30);assert.deepEqual(one.summary.map(p=>p.total),[28,2]);assert.equal(one.members.filter(m=>m.isOwner).length,2);const last=await readMembers(db,{page:9999});assert.equal(last.page,2);});
test('member filters, Persian search and literal wildcards match the export on all pages',async()=>{const db=database();assert.equal((await readMembers(db,{q:'علی'})).total,1);assert.equal((await readMembers(db,{q:'۱'})).total,13);assert.equal((await readMembers(db,{q:'%_'})).total,1);assert.equal((await readMembers(db,{q:"' OR 1=1 --"})).total,0);assert.equal((await readMembers(db,{status:'stopped'})).total,1);assert.equal((await readMembers(db,{status:'unavailable'})).total,1);const exported=await exportMembers(db,{platform:'telegram',status:'active',page:2});assert.equal(exported.length,27);assert(exported.every(m=>m.status==='active'&&m.platform==='telegram'));assert.equal((await readMembers(new D1())).total,0);});
test('reports reconcile counts and distinguish accounts, groups, channels, and unknown results',async()=>{const db=database();db.sqlite.exec(`INSERT INTO campaigns(id,source_platform,owner,created) VALUES(1,'bale',1,'2026-10-01 08:00:00'); INSERT INTO destinations(platform,chat,title,kind) VALUES('telegram',-3,'گروه آلیس','group'),('bale',55,'کانال آلیس','channel');`);const insert=db.sqlite.prepare('INSERT INTO outbox(platform,chat,campaign,destination,status,payload) VALUES(?,?,1,?,?,?)');for(const r of [['telegram',1,0,'sent'],['telegram',2,0,'failed'],['telegram',-3,1,'pending'],['bale',1,0,'sending'],['bale',55,1,'unknown']])insert.run(...r,JSON.stringify({text:'اعلام بازگشایی'}));const r=await readCampaignReport(db,1);assert.deepEqual(r.total,{total:5,sent:1,failed:1,pending:2,unknown:1});assert.equal(r.platforms[0].members.total,2);assert.equal(r.platforms[0].groups.pending,1);assert.equal(r.platforms[1].channels.unknown,1);assert.equal(r.status,'sending');const text=formatCampaignReport(r);assert.match(text,/اعلام بازگشایی/);assert.match(text,/تهران/);assert.match(text,/کانال‌ها/);assert.match(text,/نتیجهٔ نامشخص/);assert.match(text,/خوانده/);assert(text.length<4096);assert.equal((await recentCampaignReports(db))[0].id,1);assert.equal(await readCampaignReport(db,99),null);});
test('terminal failures never appear as full success and zero destinations have no fabricated counts',async()=>{const db=new D1();db.sqlite.exec(`INSERT INTO campaigns(id,source_platform,owner) VALUES(1,'telegram',1),(2,'bale',1); INSERT INTO outbox(platform,chat,campaign,payload,status) VALUES('telegram',1,1,'{}','unknown');`);assert.equal((await readCampaignReport(db,1)).status,'attention');assert.equal((await readCampaignReport(db,2)).status,'empty');assert.match(formatCampaignReport(null),/هنوز/);});
test('owner signatures reject other accounts, modified payloads, duplicates, expiry and wrong platform secrets',async()=>{const secret='ab'.repeat(32),time=1800000000;function sign(id,at=time){const p=new URLSearchParams({auth_date:String(at),user:JSON.stringify({id,first_name:'مدیر'})});const check=[...p].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+'='+v).join('\n');p.set('hash',createHmac('sha256',Buffer.from(secret,'hex')).update(check).digest('hex'));return p.toString()};assert.equal((await validateTelegram(sign(10),secret,'10',time)).id,10);assert.equal(await validateTelegram(sign(11),secret,'10',time),null);assert.equal(await validateTelegram(sign(10,time-3601),secret,'10',time),null);assert.equal(await validateTelegram(sign(10), 'cd'.repeat(32),'10',time),null);assert.equal(await validateTelegram(sign(10)+'&user={}',secret,'10',time),null);});
test('Excel export preserves IDs as text and names as literal strings, not formulas',()=>{const bytes=membersXlsx([{id:'001234',name:'=HYPERLINK("https://example.com") & <آلیس>',platform:'bale',created:'2026-10-01 08:00:00',status:'active',isOwner:false}]);const zip=unzipSync(bytes);const xml=strFromU8(zip['xl/worksheets/sheet1.xml']);assert.match(xml,/001234/);assert.match(xml,/&amp;/);assert.match(xml,/&lt;آلیس&gt;/);assert.match(xml,/t="inlineStr"/);assert(!xml.includes('<f>'));assert.match(xml,/rightToLeft="1"/);assert(zip['[Content_Types].xml']);});
