import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { handleUpdate, contentOf, eventKey } from '../src/flow.js';
import { drain } from '../src/index.js';

class D1 {
  constructor(){this.sqlite=new DatabaseSync(':memory:');for(const name of ['0001_initial.sql','0002_broadcast_flow.sql'])this.sqlite.exec(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8'));}
  withSession(){return this;}
  prepare(sql){
    const db=this;let args=[];
    return {bind(...values){args=values;return this;},async first(){return db.sqlite.prepare(sql).get(...args)||null;},async all(){return {results:db.sqlite.prepare(sql).all(...args)};},async run(){return this.execute();},execute(){const r=db.sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}};}};
  }
  async batch(statements){this.sqlite.exec('BEGIN');try{const out=statements.map(s=>s.execute());this.sqlite.exec('COMMIT');return out;}catch(e){this.sqlite.exec('ROLLBACK');throw e;}}
  rows(sql,...args){return this.sqlite.prepare(sql).all(...args);}
}
function setup(){const env={DB:new D1(),TELEGRAM_OWNER_ID:'10',BALE_OWNER_ID:'20',TELEGRAM_BOT_TOKEN:'test-tg',BALE_BOT_TOKEN:'test-bale'};env.DB.sqlite.exec(`INSERT INTO members(platform,chat) VALUES('telegram',10),('telegram',11),('bale',20),('bale',21); INSERT INTO destinations(platform,chat,title,kind,active) VALUES('telegram',-30,'گروه الف','group',1),('bale',40,'کانال ب','channel',1),('bale',41,'غیرفعال','channel',0);`);return env;}
let seq=0;
function message(platform,text,extra={}){return {update_id:++seq,message:{message_id:seq,date:100000+seq,from:{id:platform==='telegram'?10:20,first_name:'مدیر'},chat:{id:platform==='telegram'?10:20,type:'private'},text,...extra}};}
function draft(env,p){return env.DB.rows('SELECT * FROM drafts WHERE platform=?',p)[0];}
function callback(p,key,action,extra={}){return {update_id:++seq,callback_query:{id:`c${seq}`,from:{id:p==='telegram'?10:20},data:`bc:${key}:${action}`,message:{message_id:500,chat:{id:p==='telegram'?10:20,type:'private'}},...extra}};}
async function prepare(env,p='bale',text='اطلاعیهٔ آزمایشی'){await handleUpdate(env,p,message(p,text));return JSON.parse(draft(env,p).payload).key;}
function campaigns(env){return env.DB.rows('SELECT * FROM campaigns');}
function deliveries(env){return env.DB.rows('SELECT * FROM outbox WHERE campaign IS NOT NULL');}

for(const platform of ['telegram','bale']) {
  test(`${platform}: send content then choose members of BOTH bots`,async()=>{const env=setup();await handleUpdate(env,platform,message(platform,'ارسال همگانی'));assert.equal(draft(env,platform).stage,'content');const key=await prepare(env,platform);const selector=JSON.parse(env.DB.rows('SELECT payload FROM outbox ORDER BY id DESC LIMIT 1')[0].payload);assert.equal(selector.reply_markup.inline_keyboard.length,5);await handleUpdate(env,platform,callback(platform,key,'members'));assert.deepEqual(deliveries(env).map(x=>x.platform).sort(),['bale','bale','telegram','telegram']);assert.equal(draft(env,platform),undefined);});
  test(`${platform}: groups only never sends to members`,async()=>{const env=setup();const key=await prepare(env,platform);await handleUpdate(env,platform,callback(platform,key,'groups_all'));assert.equal(deliveries(env).length,2);assert.ok(deliveries(env).every(r=>r.destination===1));});
  test(`${platform}: everyone covers both bots and active groups`,async()=>{const env=setup();const key=await prepare(env,platform);await handleUpdate(env,platform,callback(platform,key,'all'));assert.equal(deliveries(env).length,6);assert.equal(new Set(deliveries(env).map(r=>`${r.platform}:${r.chat}`)).size,6);});
  test(`${platform}: selected destinations span platforms without exposing IDs`,async()=>{const env=setup();const key=await prepare(env,platform);await handleUpdate(env,platform,callback(platform,key,'choose'));const data=JSON.parse(draft(env,platform).payload);const selector=JSON.parse(env.DB.rows('SELECT payload FROM outbox ORDER BY id DESC LIMIT 1')[0].payload);assert.ok(!JSON.stringify(selector.reply_markup).includes('40'));for(let i=0;i<data.places.length;i++)await handleUpdate(env,platform,callback(platform,key,'g'+i));await handleUpdate(env,platform,callback(platform,key,'send'));assert.equal(deliveries(env).length,2);});
}
test('duplicate webhooks and concurrent double clicks produce one campaign',async()=>{const env=setup();const key=await prepare(env);const update=callback('bale',key,'all');await Promise.all([handleUpdate(env,'bale',update),handleUpdate(env,'bale',update),handleUpdate(env,'bale',callback('bale',key,'all'))]);assert.equal(campaigns(env).length,1);assert.equal(deliveries(env).length,6);});
test('failed transaction leaves draft and update retryable, with no partial campaign',async()=>{const env=setup();const key=await prepare(env);const batch=env.DB.batch.bind(env.DB);env.DB.batch=async()=>{throw new Error('D1 unavailable');};const update=callback('bale',key,'all');await assert.rejects(handleUpdate(env,'bale',update));assert.equal(campaigns(env).length,0);assert.ok(draft(env,'bale'));env.DB.batch=batch;await handleUpdate(env,'bale',update);assert.equal(deliveries(env).length,6);});
test('new content invalidates old buttons; cancel never publishes',async()=>{const env=setup();const old=await prepare(env);const key=await prepare(env,'bale','پیام جدید');assert.match(await handleUpdate(env,'bale',callback('bale',old,'all')),/قبلاً/);await handleUpdate(env,'bale',callback('bale',key,'cancel'));await handleUpdate(env,'bale',callback('bale',key,'all'));assert.equal(campaigns(env).length,0);});
test('expired selectors explain recovery; next message creates fresh draft',async()=>{const env=setup();const key=await prepare(env);env.DB.sqlite.exec('UPDATE drafts SET expires=1');assert.match(await handleUpdate(env,'bale',callback('bale',key,'all')),/زمان/);const next=await prepare(env);assert.notEqual(next,key);assert.equal(campaigns(env).length,0);});
test('ordinary users and forged callbacks cannot publish',async()=>{const env=setup();const key=await prepare(env);await handleUpdate(env,'bale',callback('bale',key,'all',{from:{id:21}}));await handleUpdate(env,'bale',message('bale','ارسال همگانی',{from:{id:21},chat:{id:21,type:'private'}}));assert.equal(campaigns(env).length,0);assert.equal(env.DB.rows('SELECT * FROM drafts').length,1);});
test('empty or disconnected selections keep the message ready',async()=>{const env=setup();const key=await prepare(env);await handleUpdate(env,'bale',callback('bale',key,'choose'));assert.match(await handleUpdate(env,'bale',callback('bale',key,'send')),/مخاطبی/);await handleUpdate(env,'bale',callback('bale',key,'g0'));env.DB.sqlite.exec('UPDATE destinations SET active=0');assert.match(await handleUpdate(env,'bale',callback('bale',key,'send')),/فعال نیست/);assert.equal(campaigns(env).length,0);});
test('legacy reply buttons cannot become a broadcast; /start exits composer',async()=>{const env=setup();await handleUpdate(env,'bale',message('bale','ارسال به همهٔ اعضا و گروه‌ها'));assert.equal(draft(env,'bale'),undefined);await prepare(env);await handleUpdate(env,'bale',message('bale','/start'));assert.equal(draft(env,'bale'),undefined);});
test('Bale string IDs work and reused update IDs do not hide new messages',async()=>{const env=setup();const one=message('bale','اول',{from:{id:'20'},chat:{id:20,type:'private'}});const two=message('bale','دوم');two.update_id=one.update_id;await handleUpdate(env,'bale',one);await handleUpdate(env,'bale',two);assert.equal(JSON.parse(draft(env,'bale').payload).content.text,'دوم');assert.notEqual(eventKey('bale',one),eventKey('bale',two));});
test('media validation and cross-platform file transfer flags',async()=>{assert.match(contentOf({media_group_id:'a',photo:[{file_id:'p'}]}).error,/آلبوم/);assert.match(contentOf({video:{file_id:'v',file_size:21*1024*1024}}).error,/۲۰/);const env=setup();await handleUpdate(env,'bale',message('bale',undefined,{video:{file_id:'v',file_size:5000},caption:'خبر'}));const key=JSON.parse(draft(env,'bale').payload).key;await handleUpdate(env,'bale',callback('bale',key,'all'));for(const r of deliveries(env)){const p=JSON.parse(r.payload);assert.equal(r.method,'sendVideo');assert.equal(p._media_source,r.platform==='telegram'?'bale':undefined);}});
test('large audiences enqueue atomically',async()=>{const env=setup();for(let i=100;i<800;i++)env.DB.sqlite.prepare("INSERT INTO members(platform,chat) VALUES('bale',?)").run(i);const key=await prepare(env);await handleUpdate(env,'bale',callback('bale',key,'all'));assert.equal(deliveries(env).length,706);});
test('drain prioritizes controls, continues between invocations, and reports completion once',async(t)=>{const env=setup();const key=await prepare(env);await handleUpdate(env,'bale',callback('bale',key,'all'));const sent=[];t.mock.method(globalThis,'fetch',async(url,opts)=>{sent.push({url,body:JSON.parse(opts.body)});return Response.json({ok:true,result:{message_id:12}});});await drain(env,2,{pauseMs:0});assert.equal(deliveries(env).filter(x=>x.status==='sent').length,0);await drain(env,12,{pauseMs:0});assert.ok(deliveries(env).every(x=>x.status==='sent'));assert.equal(sent.filter(x=>x.body.text?.startsWith('ارسال پایان یافت')).length,1);await drain(env,12,{pauseMs:0});assert.equal(sent.filter(x=>x.body.text?.startsWith('ارسال پایان یافت')).length,1);});
test('429 retries, permission failures explain reason, uncertain delivery is not repeated',async(t)=>{const env=setup();const key=await prepare(env);await handleUpdate(env,'bale',callback('bale',key,'all'));env.DB.sqlite.exec("UPDATE outbox SET status='sent' WHERE campaign IS NULL");let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;if(calls===1)return Response.json({ok:false,error_code:429,parameters:{retry_after:30}});if(calls===2)return Response.json({ok:false,error_code:403});if(calls===3)throw new Error('network');return Response.json({ok:true,result:true});});await drain(env,6,{pauseMs:0});assert.equal(deliveries(env).filter(x=>x.status==='pending').length,1);assert.equal(deliveries(env).filter(x=>x.status==='failed').length,1);assert.equal(deliveries(env).filter(x=>x.status==='unknown').length,1);assert.equal(env.DB.rows('SELECT * FROM delivery_errors').length,3);await drain(env,4,{pauseMs:0});assert.equal(calls,6);});
test('queue lease prevents concurrent delivery; stale claims become unknown',async(t)=>{const env=setup();await prepare(env);env.DB.sqlite.exec("UPDATE outbox SET status='sending',due=1");t.mock.method(globalThis,'fetch',async()=>Response.json({ok:true,result:true}));await Promise.all([drain(env,4,{pauseMs:0}),drain(env,4,{pauseMs:0})]);assert.equal(env.DB.rows('SELECT status FROM outbox')[0].status,'unknown');});
